### ISSUE TITLE
Support environment variable access from yml files

### ISSUE THREAD

**Issue by tamj0rd2** [tamj0rd2/ncdc#376]
## Summary

Right now it's not really possible to test basic auth headers unless you're comfortable with putting that plain text information into a config file. There should be some way to read the username/password from environment variables

Not possible to run tests or check for basic auth headers without putting them into the config in plain text

process.env inside of ncdc. Not sure what the config option would look like though. Possibly:

```yaml
- name: Book
  request:
    method: GET
    endpoints:
      - /api/books/123
      - /api/books/456
    serveEndpoint: /api/books/*
    basicAuth:
      username: {{ BOOKS_API_USERNAME }}
      password: {{ BOOKS_API_PASSWORD }}
  response:
    code: 200
    headers:
      content-type: application/json
    type: Book
    serveBody:
      {
        ISBN: "9780141187761",
        ISBN_13: 978-0141187761,
        author: George Orwell,
        title: 1984 Nineteen Eighty-Four,
        inventoryId: item-87623
      }
```
