### ISSUE TITLE
response.headers

### ISSUE THREAD

**Issue by tamj0rd2** [tamj0rd2/ncdc#7]
### response.headers (pending changes)

- **Description**: The headers you expect to receive from the endpoint. Header
  names are case insensitive
- **Type**: object
- **Required?**: No
- **Example**:
  ```yaml
  headers:
    content-type: application/json
    Cache-Control: no-cache
  ```
